version: "{build}"

# Source Config

clone_folder: c:\gopath\src\github.com\ActiveState\cli

# Build host

environment:
  GOBIN: c:\\\gopath\\\bin\\\
  GOROOT: C:\\\go\\\
  GOPATH: c:\\\gopath\\\
  DEPTESTBYPASS501: 1
  GOVERSION: 1.9
  AWS_ACCESS_KEY_ID: AKIAIEHTSQLDGOG22JNQ
  AWS_SECRET_ACCESS_KEY: 
    secure: t/l4poF0SydEXopKK9AUHxV9ueYKhTBucN//x6D3WelSJztOuSE5q8+4LBrSd/zO
  priv_key:
    secure: x7NykL3qJk4REp1Rr5cXIzB3XSTnU5wz99GwjMOWqHU6T7L6yviSFDcjwHtpxpqM6GFgWe0zwdQUho81Zd2ppA3v+Fq3CC97lBYYnKmqvLr+c8G5jsIQ/UmBvvk1J+1Olspb4CrksWNV8Hc//cJEMvuc+TQOdL5dsUIP1nmSGaW1oobN+eWZJoSiB8UHqtumMxWsOJbJFs154kU26InnnDWy2q6VFFL2zr4SN6z1vo53cMtF5RNAxWg2B1oHxgZlkmqdq/J04x0Q4cJWOImC9ZAIHmZp4dLq4hR83u4ClOMp/63aDx4YPeRS3uyCdjUqSSWAVaHU7J9BeeMQsYH9v+rDgA2GFOAXLozS7SJT9Kz7FBkV9rJGbeE73+5BqKdLZ80/LAryDOdZE79cBE54TrA5gODY6dT3sh+wqBhhpb0e9wXbDP9SEnSgMZ8gw8P7fmJ8oXKPu2jBfUAYv1TMA/uaB3nZQ5L8VafreGJACC46EHVg9XS4nVJSuVamfgMKiNMXOfkt1oGaAz6bM34KLT0rJKN4WbMVZTS6Lr1q8KSrvSCsZmiuJawwp6GMVPK/IL0Kel6lfKhX65NA2k6u2mpr1mVmXJJNidjLHRKTvRxJKM8uG1XvVHCcRdccLl8xoRzaneock4WhFIpwIzX89wAT6yQA6ZSPc82aggH7E2AZstY0yQMxB8n/si+3h/Nt9/Jr1etczZPRTR++igbifjVWQeEXPkmH1Eyl8R/8fz5rasEXJwt7XmkHGdvJ6yeQ7q0oGI6x3pPrKbh2H4vjnC4ScVkqDrow2JQvCYwLwFBVHdK4ly1UKclZrJsuocIavUwkjDqZkMfzM/LerSIBuzog0adhvn8fcaikKWzU+2tN4PEmLlXHQsV52jBCF5bf4j4P0uI+QrWht+sXH5OOaz5fF873DpBa9zwp/O9zFpZTXNEjQc01WiNTWLMOKTv/XlsXZdsLYef8B6Mo2/3rh/0qaR4zogrvSAMsPiV+uujsSaLw43ppkF1jltO+SyX00/UcAoCwgXH8jQP4vWnPmF2V0I8a8460sdsCarGa9hKxEB+suFS6ubvwa9SfBCVNA2f62LkT4IA2KZmWgxnmGRqt/vF3+iYKvBTUYGeRDRc6XVQSegOAx0ORNm7KCGC2Q0skCZXeKnZX2I5yPS6WNazUtP5wQx2L4b1KOLsNL2n7wrOCYK1n9MY/uxf828gSe7Zj0UMSHebwsUgPCkTgSVCJUFSsbddyjOVB91portTFzyeBcSGLkFU7N/MENo+9sp/aMlva1kn8/m+3+I32NGv6wgWLVosZ8508kgx0XHKIHHmJtzcdnezi2BNNI856BpEqnmvDG+Ey3kZnTkxHWDn9/YX1kx0wZQpe3QfUoaKbwHzetYGCBSb90lFYHkPTe72CNsDYQPCYdX454fYIYom2/MG4xYodAQtx+Di+PmHLH7KqPqHJTmSOWqjGy98Z/PuRLJoGKEFuAsMYO5ySfSAvP97Is68Bx02OGys6Zjtf0YEu+g1zqktW0GA1/G1H1b0pOyAJigXdopGAG4zrKQ8ZkN87yPqwKtRhkD7eQj/vHEVVosnzYA9As6gDYZwL7rR6tn7UJ9QnQX2oRnx6CgOlemXG59aXbuVo4DREIIEPn+0mOFoJqMdU8fgJ5uI64UqQfjWOZiI05KJCN7VxOpkccU0hgSLdwTRbhi/HVIG/e9XXCWi5TQWOunjIQn7yEu+uPkfg5F1QZp87buMC22d3RSzupRT7tqFgpzUQc2FTWDPQLlgI6shE5IXzEdb60gDR6+lnMpsdy1E/+xEHux6Xp8AeGU9RpE3nNwPFT42ii7DIRjenveakp5OvLD5Hsz0UbP9arKno2ju6fu8/n7J5Yj3tPBvfRORZUaqCbJ13vFWGPbesEBXoYFceyruhoeoj8nVs7vwowT9xktH+OjLTbm1hHB1Iy3IfusjnjbT4zz3GUxSFnMRuJZPuhdJZZzBo4qzzKwkhjtBly/FQzLe9/9s+RLyL9pMpqJYoEJu839T8m2X017IkQJM/MXeaEDPZ/QAfNQpAI0P9EvYwF3YAn6Z0+tX78j6vqGeOAeB5D4Y9L4ps54T192Ad8H3EpbIashBhg3yrEyQmrlB8VSUd3on+yn1UAEVfMny6IuniBmthlxdk5hzKQ1iMMyIX

  
init:
  - git config --global core.autocrlf input

#  Cache Go install
cache:
  - C:\go\

# Build

install:
  # Install the specific Go version.
  - ps: $fileContent = "-----BEGIN RSA PRIVATE KEY-----`n"
  - ps: $fileContent += $env:priv_key.Replace(' ', "`n")
  - ps: $fileContent += "`n-----END RSA PRIVATE KEY-----"
  - ps: Set-Content $env:userprofile\.ssh\id_rsa $fileContent
  - git submodule update --init
  - choco install make
  - IF EXIST C:\go (echo We already have GO installed) ELSE (appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi && msiexec /i go%GOVERSION%.windows-amd64.msi /q TARGETDIR=%GOROOT%)
  - go get -u github.com/gobuffalo/packr/...

notifications:
   - provider: Slack
     on_build_success: false
     on_build_failure: true
     on_build_status_changed: true
     incoming_webhook:
       secure: 0kmyFqWrTagxfzJJe5KYrRjcs+xNdwAlt8eWt0bqyt/6w0bXPHNZRP6k9Ixxubt5EjWG0JWswA0UBZPLOmhSI5BFhyjsl3N+EisrpOCG1BU=

# Turns off MSBUILD which automatically builds a VS project.
build: false
deploy: false

test_script:
  - make build
  - make test