ignored = ["github.com/dave/jennifer"]

[[constraint]]
  branch = "master"
  name = "github.com/spf13/viper"
  
[[constraint]]
  branch = "master"
  name = "github.com/vbauerster/mpb"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/jarcoal/httpmock.v1"

[[constraint]]
  name = "github.com/ActiveState/archiver"
  version = "3.1.1"
