# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
defaults:
  steps:
    prepareEnv: &prepareEnv
      run:
        name: Prepare Environment
        command: |
          git submodule update --init
          mkdir -p $TEST_RESULTS
          $GOROOT/bin/go get github.com/jstemmer/go-junit-report
          $GOROOT/bin/go get -u github.com/gobuffalo/packr/packr
          $GOROOT/bin/go run scripts/constants-generator/main.go -- internal/constants/generated.go
          ./public/install.sh -n -b master
          echo "export PATH=$HOME/.local/bin:${GOROOT}/bin:${GOPATH}/bin:${PATH}:$PATH" >> $BASH_ENV
    runTests: &runTests
      run:
        name: Run unit tests
        command: |
          /tmp/cc-test-reporter before-build
          $GOROOT/bin/go test -parallel 12 -covermode=atomic -coverprofile=c.out `$GOROOT/bin/go list ./... | grep -v api` | tee ${TEST_RESULTS}/go-test.out
          $GOBIN/go-junit-report < ${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml
          /tmp/cc-test-reporter after-build --coverage-input-type gocov --exit-code $?
          ~/.local/bin/state auth $PLATFORM_API_TOKEN # Tests appear to be breaking the authentication
    buildCli: &buildCli
      run:
        name: Build the CLI
        command: |
          $GOBIN/packr
          BRANCH=$(git rev-parse --abbrev-ref HEAD)

          echo "Building for internal use"
          APIENV=prod state run build

          if [[ "$BRANCH" == "master" ]]; then
            echo "Building for external use"
            APIENV=prod BRANCH_OVERRIDE=unstable state run build-external
          fi
    deployBits: &deployBits
      run:
        name: Deploy bits
        command: state run deploy-updates
    storeArtifacts: &storeArtifacts
      store_artifacts:
        path: /tmp/test-results
        destination: raw-test-output
    storeTestResults: &storeTestResults
      store_test_results:
        path: /tmp/test-results
jobs:
  build-linux:
    environment:
      TEST_RESULTS: /tmp/test-results
      GOBIN: /go/bin
      GOPATH: /go
      GOROOT: /usr/local/go
      SHELL: bash
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/ActiveState/cli
    steps:
      - checkout
      - run:
          name: Prepare Code-Climate Integration
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.6.3-linux-amd64 > /tmp/cc-test-reporter
            chmod +x /tmp/cc-test-reporter
      - <<: *prepareEnv
      - run:
          name: Authenticate State Tool
          command: ~/.local/bin/state auth $PLATFORM_API_TOKEN
      - <<: *runTests
      - <<: *buildCli
      - <<: *deployBits
      - <<: *storeArtifacts
      - <<: *storeTestResults
  build-macos:
    environment:
      TEST_RESULTS: /tmp/test-results
      GOPATH: /private/tmp/gohome
      GOBIN: /private/tmp/gohome/bin
      GOROOT: /private/tmp/go
      SHELL: bash
    macos:
      xcode: 9.2.0
    working_directory: /private/tmp/gohome/src/github.com/ActiveState/cli
    steps:
      - checkout
      - run:
          name: Install Golang
          command: |
            cd /private/tmp
            curl https://dl.google.com/go/go1.9.5.darwin-amd64.tar.gz -o golang.tar.gz
            tar -xzf golang.tar.gz
      - run:
          name: Prepare Code-Climate Integration
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.6.3-darwin-amd64 > /tmp/cc-test-reporter
            chmod +x /tmp/cc-test-reporter
      - <<: *prepareEnv
      - run:
          name: Authenticate State Tool
          command: state auth $PLATFORM_API_TOKEN
      - run:
          name: Run unit tests
          command: |
            state run test
      - <<: *buildCli
      - <<: *deployBits
      - <<: *storeArtifacts
      - <<: *storeTestResults
workflows:
  version: 2
  build:
    jobs:
      - build-linux
      - build-macos:
          requires:
            - build-linux
