trigger:
  - master

jobs:
  - job: build_windows_azure
    pool:
      vmImage: vs2017-win2016
    variables:
      - group: Secrets
      - name: SHELL
        value: /c/Program\ Files/Git/bin/bash.exe
      - name: CI
        value: azure
      - name: GOPATH
        value: /c/Users/VssAdministrator/go
      - name: GOBIN
        value: /c/Users/VssAdministrator/go/bin
      - name: GOFLAGS
        value: -mod=vendor
      - name: BINPATH
        value: /c/Users/VssAdministrator/bin
      - name: MODPATH
        value: /c/Users/VssAdministrator/$(build.repository.name)
      - name: WORKDIR
        value: C:\Users\VssAdministrator\$(build.repository.name)
      - name: ACTIVESTATE_CLI_DISABLE_RUNTIME
        value: "true"
      - name: ACTIVESTATE_CLI_DISABLE_UPDATES
        value: "true"
    steps:
      - bash: |
          set -e
          mkdir -p $(BINPATH)
          mkdir -p $(GOPATH)
          mkdir -p $(GOBIN)
          mkdir -p $(MODPATH)
          shopt -s dotglob nullglob
          mv "$(system.defaultWorkingDirectory)/"* $(MODPATH)
          echo '##vso[task.prependpath]$(GOBIN)'
          echo '##vso[task.prependpath]$(BINPATH)'
          echo '##vso[task.prependpath]$(MODPATH)/.azure'

          go version
        displayName: Prepare Environment
      - bash: |
          ./public/install.sh -b master -n -t $(BINPATH)
        workingDirectory: $(WORKDIR)
        displayName: Install State Tool
      - bash: |
          set -e
          state auth --token $(PLATFORM_API_TOKEN)
          state run preprocess

          go -mod=vendor test -v -parallel 12 -covermode=atomic -coverprofile=c.out `go list ./... | grep -vE "(secrets-)?api/(client|model)"` | tee go-test.out
          go-junit-report < go-test.out > $(Agent.OS)-tests.xml
          cp go-test.out public/$(Agent.OS)-tests.out
          cp $(Agent.OS)-tests.xml public
        workingDirectory: $(WORKDIR)
        displayName: Unit Tests
      - bash: |
          set -e
          state auth --token $(PLATFORM_API_TOKEN)
          if [[ "$BUILD_SOURCEBRANCHNAME" == "master" ]]; then
            echo "Building for external use"
            APIENV=prod BRANCH_OVERRIDE=origin/unstable state run build-external
          fi
          echo "Building for internal use"
          APIENV=prod state run build
        workingDirectory: $(WORKDIR)
        displayName: Build
      - script: |
          set SHELL=
          cd test\integration
          pip3 install -r requirements.txt
          python -m unittest discover -p "*_test.py"
        workingDirectory: $(WORKDIR)
        condition: eq(variables['Agent.OS'], 'Windows_NT')
        displayName: Windows Integration Tests
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: $(WORKDIR)/public
          parallel: true
          parallelCount: 8
      - task: PublishTestResults@2
        inputs:
          searchFolder: $(WORKDIR)
          testResultsFormat: JUnit
          testResultsFiles: "*-tests.xml"
          failTaskOnFailedTests: true
