name: Build-Test-Deploy

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest] # , macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: prepare
        run: |
          set -e

          # Don't run from project dir as that will pull in deps we don't need
          pushd /
          go get github.com/jstemmer/go-junit-report
          go get github.com/gobuffalo/packr/packr
          popd

          ./public/install.sh -n -b master

          echo "::add-path::$HOME/.local/bin"
      - name: build
        run: |
          set -e
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          if [[ "$BRANCH" == "master" ]]; then
            export BRANCH_OVERRIDE=unstable
          fi
          state run build
          state run generate-update