name: Build-Test-Deploy

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest] # , macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    env:
      ACTIVESTATE_CLI_DISABLE_RUNTIME: true # We don't need Perl or Python
      GOFLAGS: -mod=vendor
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: prepare
        run: |
          pushd /
          go get github.com/gobuffalo/packr/packr
          popd

          ./public/install.sh -n -b master
          echo "::add-path::$HOME/.local/bin"
          state run preprocess
      - name: build
        run: |
          set -e
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          if [[ "$BRANCH" == "master" ]]; then
            export BRANCH_OVERRIDE=unstable
          fi
          state run build
          state run generate-update
      - name: integration tests
        run: go test -timeout 20m ./test/integration -v
  unit-test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest] # , macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    env:
      GOFLAGS: -mod=vendor
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: prepare
        run: |
          pushd /
          go get github.com/gobuffalo/packr/packr
          popd

          ./public/install.sh -n -b master
          echo "::add-path::$HOME/.local/bin"
          state run preprocess
      - name: unit tests
        run: go test -v -covermode=atomic -coverprofile=c.out `$GOROOT/bin/go list ./... | grep -v api | grep -v integration | grep -v expect`