name: Build-Test-Deploy
"on":
  push:
    branches:
    - master
  pull_request:
    types:
    - labeled
    - opened
    - synchronize
    - reopened
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Test
      shell: bash
      run: |
        echo ${{ contains(github.event.pull_request.labels.*.name, 'version:') }}
        if [ "${{ contains(github.event.pull_request.labels.*.name, 'version:') }}" -ne "true" ]; then
          echo "Version label must be set"
          exit 1
        fi
