name: Integration Test
"on":
  schedule:
  - cron: 0 0 * * *
jobs:
  inttest:
    name: Integration Test
    strategy:
      matrix:
        go-version:
        - 1.13.x
        platform:
        - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    env:
      ACTIVESTATE_CLI_DISABLE_RUNTIME: true
      GOFLAGS: -mod=vendor
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install State Tool
      run: |
        ./installers/install.sh -n -b master
        echo "::add-path::$HOME/.local/bin"
    - name: Build
      run: |
        echo "Branch: $GITHUB_HEAD_REF"
        if [[ "$GITHUB_HEAD_REF" == "master" ]]; then
          export BRANCH_OVERRIDE=unstable
        fi
        state run build
    - name: Integration Tests
      run: go test -timeout 20m ./test/integration -v
