#@ load("jobs.lib.yml", "jobs_build", "jobs_build_msi", "jobs_deploy", "jobs_unittest")
name: Build-Test-Deploy

"on":
  push:
    branches:
      - master
  pull_request:

jobs:
  build: #@ jobs_build()
  build_msi: #@ jobs_build_msi()
  unittest: #@ jobs_unittest()
  deploy: #@ jobs_deploy()
