#@ load("jobs.lib.yml", "jobs_build", "jobs_unittest")
name: Build-Test-Deploy

on:
  push:
    branches:
      - master
  pull_request:
    - master

jobs:
  - #@ jobs_build()
  - #@ jobs_unittest()
