#@ load("steps.lib.yml", "steps_preprocess", "steps_build", "steps_genupdate", "steps_installgo", "steps_installstate", "steps_test", "steps_inttest", "steps_uploadartifacts", "steps_downloadartifacts", "steps_deploy", "steps_build_state_msi", "steps_build_languages_msi")

strategy: &strategy
  matrix:
    go-version: [1.13.x]
    platform: [ windows-latest ] # , [ ubuntu-latest, macos-latest, windows-latest]
runs-on: &runs-on ${{ matrix.platform }}
env: &env
  ACTIVESTATE_CLI_DISABLE_RUNTIME: true # We don't need Perl or Python
  GOFLAGS: -mod=vendor
  SHELL: bash
  GITHUB_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#@ def jobs_build():
name: Build
strategy: *strategy
runs-on: *runs-on
env: *env
steps:
  - name: "Checkout code"
    uses: actions/checkout@v2
  - #@ steps_installgo()
  - #@ steps_installstate()
  - #@ steps_build()
  - #@ steps_genupdate()
  - #@ steps_uploadartifacts()
#@ end

#@ def jobs_build_msi():
name: Build MSI's
runs-on: windows-latest
needs: build
env: *env
steps:
  - name: "Checkout code"
    uses: actions/checkout@v2
  - #@ steps_downloadartifacts()
  - #@ steps_installgo()
  - #@ steps_installstate()
  - #@ steps_build_state_msi()
  - #@ steps_build_languages_msi()
  - #@ steps_uploadartifacts()
#@ end

#@ def jobs_unittest():
name: "Unit Test"
strategy: *strategy
runs-on: *runs-on
env: *env
steps:
  - name: "Checkout code"
    uses: actions/checkout@v2
  - #@ steps_installgo()
  - #@ steps_installstate()
  - #@ steps_preprocess()
  - #@ steps_test()
#@ end

#@ def jobs_inttest():
name: "Integration Test"
strategy: *strategy
runs-on: *runs-on
env: *env
steps:
  - name: "Checkout code"
    uses: actions/checkout@v2
  - #@ steps_installgo()
  - #@ steps_installstate()
  - #@ steps_build()
  - #@ steps_inttest()
#@ end

#@ def jobs_deploy():
name: Deploy
needs: [ build, build_msi, unittest ]
runs-on: ubuntu-latest
env: *env
steps:
  - name: "Checkout code"
    uses: actions/checkout@v2
  - #@ steps_installgo()
  - #@ steps_installstate()
  - #@ steps_downloadartifacts()
  - #@ steps_deploy()
#@ end