#@ def steps_build():
name: Build
shell: bash
run: |
  echo "Branch: $GITHUB_HEAD_REF"
  if [[ "$GITHUB_HEAD_REF" == "master" ]]; then
    export BRANCH_OVERRIDE=unstable
  fi
  state run build
#@ end
---
#@ def steps_genupdate():
name: "Generate Update"
shell: bash
run: state run generate-update
#@ end
---
#@ def steps_installgo():
name: "Install Go"
uses: actions/setup-go@v2
with:
  go-version: ${{ matrix.go-version }}
#@ end
---
#@ def steps_setup():
name: "Setup"
shell: bash
run: |
  bin=$(pwd)/.github/deps/${{ runner.os }}/bin
  echo "Adding $bin to PATH"
  echo "::add-path::$bin"
#@ end
---
#@ def steps_preprocess():
name: "Preprocess"
shell: bash
run: state run preprocess
#@ end
---
#@ def steps_test():
name: "Unit Tests"
shell: bash
run: |
  go test -v `go list ./... | grep -v api | grep -v integration | grep -v expect`
#@ end
---
#@ def steps_inttest():
name: "Integration Tests"
shell: bash
run: go test -timeout 20m ./test/integration -v
#@ end
---
#@ def steps_uploadsessartifacts():
name: "Upload Session Artifacts"
uses: actions/upload-artifact@v2
with:
  name: session-build
  path: build/
#@ end
---
#@ def steps_uploadartifacts():
name: "Upload Artifacts"
uses: actions/upload-artifact@v2
with:
  name: build
  path: build/
#@ end
---
#@ def steps_downloadsessartifacts():
name: "Download Session Artifacts"
uses: actions/download-artifact@v2
with:
  name: session-build
  path: build/
#@ end
---
#@ def steps_deletesessartifacts():
name: "Cleanup Session Artifacts"
uses: geekyeggo/delete-artifact@v1
with:
  name: session-build
#@ end
---
#@ def steps_deploy():
name: "Deploy"
shell: bash
run: |
  state run deploy-updates
  if [[ "$GITHUB_HEAD_REF" == "master" ]]; then
    state run deploy-installers
  fi
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#@ end
---
#@ def steps_build_state_msi():
name: "Build State MSI"
shell: bash
run: |
  echo $MSI_CERT_BASE64 | base64 --decode > Cert.p12
  export PATH=/c/Program\ Files\ \(x86\)/WiX\ Toolset\ v3.11/bin/:/c/Program\ Files\ \(x86\)/Windows\ Kits/10/bin/10.0.16299.0/x86/:$PATH
  export SHELL=bash
  state run build-msi-state
  signtool.exe sign -d "ActiveState State Tool" -f "Cert.p12" -p ${CODE_SIGNING_PASSWD} build/msi/state_tool.msi
env:
  CODE_SIGNING_PASSWD: ${{ secrets.CODE_SIGNING_PASSWD }}
  MSI_CERT_BASE64: ${{ secrets.MSI_CERT_BASE64 }}
#@ end
---
#@ def steps_build_languages_msi():
name: "Build Languages MSI"
shell: bash
run: |
  echo $MSI_CERT_BASE64 | base64 --decode > Cert.p12
  export PATH=/c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2019/Enterprise/MSBuild/Current/Bin/:/c/Program\ Files\ \(x86\)/Windows\ Kits/10/bin/10.0.16299.0/x86/:$PATH
  export SHELL=bash
  state run build-msi-language ActivePerl-5.26 http://docs.activestate.com/activeperl/5.26/get/relnotes/
  signtool.exe sign -d "ActiveState Language Installer" -f "Cert.p12" -p ${CODE_SIGNING_PASSWD} ./build/msi/ActivePerl-5.26.msi
  state run build-msi-language ActivePerl-5.28 http://docs.activestate.com/activeperl/5.28/get/relnotes/
  signtool.exe sign -d "ActiveState Language Installer" -f "Cert.p12" -p ${CODE_SIGNING_PASSWD} ./build/msi/ActivePerl-5.28.msi
env:
  CODE_SIGNING_PASSWD: ${{ secrets.CODE_SIGNING_PASSWD }}
  MSI_CERT_BASE64: ${{ secrets.MSI_CERT_BASE64 }}
#@ end
---
#@ def steps_cleanbuild():
name: "Cleanup Build Dir"
shell: bash
run: rm build/state* || true
#@ end